version: '3.1'

services:
  db:
    image: postgres:11.7
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: local

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
