service: grants-service

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  stage: ${opt:stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:ListBucket
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

package:
  individually: true
  exclude:
    - ./**

functions:
  additional-restrictions-grant:
    name: ${self:service}-${self:provider.stage}
    handler: lambda.handler
    timeout: 20
    package:
      include:
        - lambda.js
        - next.config.js
        - pages/**
        - public/**
        - build/_next/**
        - node_modules/**
    events:
      - http:
          path: api/{proxy+}
          method: ANY
          authorizer:
            name: authorizer
            type: request
            identitySource: ''
            resultTtlInSeconds: 0
      - http: ANY /
      - http: ANY /{proxy+}
    vpc:
      securityGroupIds:
        - ${self:custom.security-group-id.${self:provider.stage}}
      subnetIds: 
        - ${self:custom.subnets.${self:provider.stage}}
    environment:
      ENV: ${self:provider.stage}
      HOST:
        Fn::GetAtt:
          - additionalRestrictionsGrantDb
          - Endpoint.Address
      USERNAME: ${env:MASTER_USERNAME}
      PASSWORD: ${env:MASTER_USER_PASSWORD}
      DATABASE: ${self:custom.dbname}
      SUPPORTING_DOCUMENTS_BUCKET: ${self:custom.bucket}
      URL_PREFIX: ${self:custom.aliases.${self:provider.stage}}
      EXPIRATION_DATE: ${env:EXPIRATION_DATE}
      HACKNEY_AUTH_URL: ${env:HACKNEY_AUTH_URL}
      GOV_NOTIFY_API_KEY: ${env:GOV_NOTIFY_API_KEY}
      EMAIL_APPLICATION_RECEIVED_TEMPLATE_ID: ${env:EMAIL_APPLICATION_RECEIVED_TEMPLATE_ID}
      CSV_DOWNLOAD_GROUP: ${env:CSV_DOWNLOAD_GROUP}
      NEXT_PUBLIC_EQUALITIES_GOOGLE_FORM_URL: ${env:NEXT_PUBLIC_EQUALITIES_GOOGLE_FORM_URL}

  authorizer:
    name: ${self:service}-authorizer-${self:provider.stage}
    handler: authorizer.handler
    package:
      include:
        - authorizer/**
        - node_modules/**
    environment:
      ALLOWED_GROUPS: ${self:custom.allowed-groups.${self:provider.stage}}
      JWT_SECRET: ${ssm:/grants-service/${self:provider.stage}/hackney-jwt-secret}

resources:
  Resources:
    additionalRestrictionsGrantSupportingDocumentsBucket:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: ${self:custom.bucket}
          PublicAccessBlockConfiguration:
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true
          BucketEncryption:
            ServerSideEncryptionConfiguration:
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: AES256
          VersioningConfiguration:
            Status: Enabled
          CorsConfiguration:
            CorsRules:
              -
                AllowedOrigins:
                  - '*'
                AllowedHeaders:
                  - '*'
                AllowedMethods:
                  - PUT
                  - POST
                MaxAge: 3000
                
    additionalRestrictionsGrantDbSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Allow internal VPC
        VpcId: ${self:custom.vpc-id.${self:provider.stage}}
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 172.31.0.0/16

    additionalRestrictionsGrantDbSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties: 
        DBSubnetGroupDescription: "Additional Restrictions Grant DB Subnet Group"
        DBSubnetGroupName: "additionalRestrictionsGrantDb-${self:provider.stage}"
        SubnetIds: ${self:custom.subnets.${self:provider.stage}}
        Tags:
          -
            Key: "Name"
            Value: "additionalRestrictionsGrantsDb"

    additionalRestrictionsGrantDb:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: 5
        DBInstanceIdentifier: "${self:service}-db-${self:provider.stage}"
        DBInstanceClass: "db.t2.small"
        DBName: ${self:custom.dbname}
        DeletionProtection: true
        Engine: "postgres"
        EngineVersion: "11.7"
        MasterUsername: ${env:MASTER_USERNAME}
        MasterUserPassword: ${env:MASTER_USER_PASSWORD}
        MultiAZ: true
        PubliclyAccessible: false
        StorageEncrypted: true
        DBSubnetGroupName: "additionalRestrictionsGrantDb-${self:provider.stage}"
        VPCSecurityGroups:
        - Fn::GetAtt:
          - additionalRestrictionsGrantDbSecurityGroup
          - GroupId
        Tags:
          -
            Key: "Name"
            Value: "additionalRestrictionsGrantsDb"
      DeletionPolicy: "Snapshot"

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Aliases:
            - ${self:custom.aliases.${self:provider.stage}}
          PriceClass: PriceClass_100
          ViewerCertificate:
            AcmCertificateArn: ${self:custom.certificate-arn.${self:provider.stage}}
            MinimumProtocolVersion: TLSv1.2_2018
            SslSupportMethod: sni-only
          DefaultCacheBehavior:
            TargetOriginId: ${self:service}-${self:provider.stage}-custom-origin
            ViewerProtocolPolicy: 'redirect-to-https'
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: all
          Enabled: true
          Origins:
            - Id: ${self:service}-${self:provider.stage}-custom-origin
              DomainName: ${self:custom.domain-name}
              OriginPath: /${self:provider.stage}
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only

custom:
  dbname: additionalRestrictionsGrantDb
  bucket: ${self:service}-supporting-documents-${self:provider.stage}
  domain-name:
    Fn::Join:
      - '.'
      - - Ref: ApiGatewayRestApi
        - execute-api
        - eu-west-2
        - amazonaws.com
  vpc-id:
    staging: vpc-0047c1ec06d524b64
    production: vpc-0c9c2cbf1865adb9e
  security-group-id:
    staging: sg-073fdfc54e08c0b7f
    production: sg-0bc53a349b857295c
  aliases:
    staging: staging-grants-service.hackney.gov.uk
    production: grants-service.hackney.gov.uk
  certificate-arn:
    staging: arn:aws:acm:us-east-1:647298111750:certificate/9b54973b-c8d3-4f0f-8d34-50afd9b7011d
    production: arn:aws:acm:us-east-1:812721144296:certificate/b2ccc8fd-f796-42dc-86d8-4267dd0c4ded
  subnets:
    staging:
      - subnet-034d259953e54531a
      - subnet-0e0152a2fc2b42498
    production:
      - subnet-034b2a03cd4955923
      - subnet-03431a6c898502c99
  allowed-groups:
    staging: 'Additional Restrictions Grant - Staging'
    production: 'Additional Restrictions Grant - Admin'
