version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.4
  aws-cli: circleci/aws-cli@1.0.0
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  node-executor:
    docker:
      - image: cimg/node:14.18.3-browsers
  docker-python:
    docker:
      - image: circleci/python:3.7

references:
  workspace_root: &workspace_root '~'
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build-deploy-production:
    executor: aws-cli/default
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: add-dependencies
          command: sudo npm i -g serverless@^3
      - run:
          name: deploy
          command: sls deploy --verbose --stage production
          no_output_timeout: 45m

  assume-role-production:
    executor: docker-python
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: $AWS_ACCOUNT_PRODUCTION
          profile_name: default
          role: 'LBH_Circle_CI_Deployment_Role'
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - permit-deploy-production:
          type: approval
          filters:
            branches:
              only: main
      - assume-role-production:
          context: api-assume-role-regen-apps-production-context
          requires:
            - permit-deploy-production
          filters:
            branches:
              only: main
      - build-deploy-production:
          requires:
            - assume-role-production
          filters:
            branches:
              only: main
