version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.4
  aws-cli: circleci/aws-cli@1.0.0
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  node-executor:
    docker:
      - image: cimg/node:14.18.3-browsers
  docker-python:
    docker:
      - image: circleci/python:3.7

references:
  workspace_root: &workspace_root '~'
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  install-dependencies-and-test:
    executor: node-executor
    steps:
      - *attach_workspace
      - checkout
      - browser-tools/install-firefox
      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Build the application
          command: yarn build

      - run:
          name: Run unit tests
          command: yarn run unit-test

      - run:
          name: Run integration tests
          command: yarn run int-test

      - run:
          name: Run linting
          command: yarn lint

      - persist_to_workspace:
          root: *workspace_root
          paths: .

  build-deploy-staging:
    executor: aws-cli/default
    steps:
      - *attach_workspace
      - run:
          name: build
          command: yarn build
          no_output_timeout: 45m
      - run:
          name: add-dependencies
          command: yarn --production=true && yarn add serverless db-migrate
      - run:
          name: deploy
          command: yarn deploy --stage staging
          no_output_timeout: 45m
      - run:
          name: migrate
          command: yarn remote:migrate --stage staging

  build-deploy-production:
    executor: aws-cli/default
    steps:
      - *attach_workspace
      - run:
          name: deploy
          command: yarn build && yarn --production=true && sudo npm i -g serverless && sls deploy --stage production
          no_output_timeout: 45m

  assume-role-staging:
    executor: docker-python
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: $AWS_ACCOUNT_STAGING
          profile_name: default
          role: 'LBH_Circle_CI_Deployment_Role'
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws

  assume-role-production:
    executor: docker-python
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: $AWS_ACCOUNT_PRODUCTION
          profile_name: default
          role: 'LBH_Circle_CI_Deployment_Role'
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - install-dependencies-and-test
      - assume-role-staging:
          context: api-assume-role-regen-apps-staging-context
          requires:
            - install-dependencies-and-test
          filters:
            branches:
              only: feature/database-migrator
      - build-deploy-staging:
          requires:
            - install-dependencies-and-test
            - assume-role-staging
          filters:
            branches:
              only: feature/database-migrator
      # - permit-deploy-production:
      #     type: approval
      #     requires:
      #       - build-deploy-staging
      # - assume-role-production:
      #     context: api-assume-role-production-context
      #     requires:
      #       - install-dependencies-and-test
      #       - permit-deploy-production
      #     filters:
      #       branches:
      #         only: master
      # - build-deploy-production:
      #     requires:
      #       - permit-deploy-production
      #       - assume-role-production
