INSERT INTO contact_type (id, description) VALUES (1, 'Agent (Authorised to act)');
INSERT INTO contact_type (id, description) VALUES (2, 'Owner (Sole Trader)');
INSERT INTO contact_type (id, description) VALUES (3, 'Partner / Employee (Acting for)');
INSERT INTO contact_type (id, description) VALUES (4, 'PSC of Registered Company (Person with significant control)');
INSERT INTO contact_type (id, description) VALUES (5, 'Trustee (Charity)');
INSERT INTO contact_type (id, description) VALUES (6, 'Company Director');
INSERT INTO contact_type (id, description) VALUES (7, 'Other (please state):');

INSERT INTO business_size(id, description) VALUES(1, 'Micro');
INSERT INTO business_size(id, description) VALUES(2, 'Small');
INSERT INTO business_size(id, description) VALUES(3, 'Medium');
INSERT INTO business_size(id, description) VALUES(4, 'Large');

INSERT INTO business_category(id, description) VALUES(1, 'Section A: Agricultural, forestry and fishing');
INSERT INTO business_category(id, description) VALUES(2, 'Section B: Mining and quarrying');
INSERT INTO business_category(id, description) VALUES(3, 'Section C: Manufacturing');
INSERT INTO business_category(id, description) VALUES(4, 'Section D: Electricity, gas, steam and air conditioning supply');
INSERT INTO business_category(id, description) VALUES(5, 'Section E: Water supply, sewerage, waste management and remediation activities');
INSERT INTO business_category(id, description) VALUES(6, 'Section F: Construction');
INSERT INTO business_category(id, description) VALUES(7, 'Section G: Wholesale and retail trade/Repair of motor vehicles and motor cycles');
INSERT INTO business_category(id, description) VALUES(8, 'Section H: Transportation and storage');
INSERT INTO business_category(id, description) VALUES(9, 'Section I: Accommodation and food services');
INSERT INTO business_category(id, description) VALUES(10, 'Section J: Information and communication');
INSERT INTO business_category(id, description) VALUES(11, 'Section K: Financial and insurance activities');
INSERT INTO business_category(id, description) VALUES(12, 'Section L: Real estate activities');
INSERT INTO business_category(id, description) VALUES(13, 'Section M: Professional,scientific and technical activities');
INSERT INTO business_category(id, description) VALUES(14, 'Section N: Administrative and support services activities');
INSERT INTO business_category(id, description) VALUES(15, 'Section O: Public administration and defence/ Compulsory social security');
INSERT INTO business_category(id, description) VALUES(16, 'Section P: Education');
INSERT INTO business_category(id, description) VALUES(17, 'Section Q: Human health and social work activities');
INSERT INTO business_category(id, description) VALUES(18, 'Section R: Arts, entertainment and recreation');
INSERT INTO business_category(id, description) VALUES(19, 'Section S: Other service activities');
INSERT INTO business_category(id, description) VALUES(20, 'Section T: Activities of households as employers/ Undifferentiated goods and services producing activities of households for own use');
INSERT INTO business_category(id, description) VALUES(21, 'Section U: Activities of extraterritorial organisations and bodies');
